import {useEffect,useRef,useState} from 'react';
import {displayMessages} from './agentMessages';
import {errorText} from './errorText';
import {watchRun,type ConnectionState} from './sse';
type API=(path:string,method?:string,body?:unknown,key?:string)=>Promise<any>;
const status:Record<string,string>={ready:'可继续',running:'运行中',failed:'运行失败',awaiting_confirmation:'等待确认',approved:'操作已确认',completed:'已完成',cancelled:'已取消'};
export default function AgentPanel({api,token,onChanged}:{api:API;token:string;onChanged:()=>Promise<void>}){
 const [sessions,setSessions]=useState<any[]>([]);
 const [runs,setRuns]=useState<any[]>([]),[run,setRun]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [connection,setConnection]=useState<ConnectionState>('connecting'),[connectionAttempt,setConnectionAttempt]=useState(0);
 const active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const cursors=useRef(new Map<string,string>());
 const terminal=run&&['completed','approved','cancelled','failed'].includes(run.status);
 function updateRun(next:any){if(!active.current)return;setRun((previous:any)=>previous?.id===next.id&&previous.event_seq>next.event_seq?previous:next);}
 useEffect(()=>{if(!run||terminal)return;const controller=new AbortController();const id=run.id;void watchRun(id,token,cursors.current,controller.signal,async()=>{const current=await api('/agent/runs/'+id);if(!controller.signal.aborted){updateRun(current);if(current.status==='approved')await onChanged();}},state=>{if(!controller.signal.aborted)setConnection(state);}).catch(e=>{if(controller.signal.aborted)return;setConnection('stopped');setError(e instanceof Error?e.message:'进度连接中断，请从运行记录恢复');});return()=>controller.abort();},[run?.id,terminal,token,connectionAttempt]);
 // A failed sync still restarts the progress watch, otherwise a run can sit on a stopped stream until the next focus.
 useEffect(()=>{let active=true;async function sync(){try{const [r,s,current]=await Promise.all([api('/agent/runs'),api('/agent/sessions'),run?api('/agent/runs/'+run.id):Promise.resolve(null)]);if(!active)return;setRuns(r);setSessions(s);if(current)updateRun(current);}catch(e){if(active)setError(e instanceof Error?e.message:'同步失败，请重试');}finally{if(active)setConnectionAttempt(n=>n+1);}}const visible=()=>{if(document.visibilityState==='visible')void sync();};window.addEventListener('focus',visible);window.addEventListener('online',visible);document.addEventListener('visibilitychange',visible);return()=>{active=false;window.removeEventListener('focus',visible);window.removeEventListener('online',visible);document.removeEventListener('visibilitychange',visible);};},[run?.id,token]);
 const keys=useRef(new Map<string,string>());
 async function mutate(path:string,body?:unknown){const signature=JSON.stringify([path,body]);let key=keys.current.get(signature);if(!key){key=crypto.randomUUID();keys.current.set(signature,key);}const value=await api(path,'POST',body,key);keys.current.delete(signature);return value;}
 async function refresh(){if(!active.current)return;const [r,s]=await Promise.all([api('/agent/runs'),api('/agent/sessions')]);if(active.current){setRuns(r);setSessions(s);}}
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();if(active.current)await refresh();}catch(e){if(active.current)setError(e instanceof Error?e.message:'请求失败');}finally{if(active.current)setBusy(false);}}
 async function createRun(body:unknown){try{return await mutate('/agent/runs',body);}catch(error){try{await refresh();if(run&&active.current)updateRun(await api('/agent/runs/'+run.id));}catch{/* Keep the original submission error when synchronization also fails. */}throw error;}}
 async function advance(current:any){updateRun(current);for(let i=0;i<9&&active.current&&current.status==='ready';i++){current=await api('/agent/runs/'+current.id+'/advance','POST');updateRun(current);}}
 useEffect(()=>{void perform(refresh);},[]);
 return <section className="panel"><h2>一人食助手</h2><p className="muted">助手可以查询食材、推荐一餐，以及准备入库、做饭和撤销操作。每次写入前会展示具体变更，由你确认。需先在后端配置模型才能对话。</p><form onSubmit={e=>{e.preventDefault();void perform(async()=>{const body={message,...(run&&['completed','approved','cancelled'].includes(run.status)?{session_id:run.session_id,expected_session_version:run.session_version}:{})};const created=await createRun(body);setMessage('');await advance(created);});}}><label>想安排怎样的一餐？<textarea value={message} onChange={e=>setMessage(e.target.value)} required maxLength={4000} rows={3} placeholder="看看冰箱里的食材，推荐一道20分钟内能做好的菜"/></label><button disabled={busy||!message.trim()||!!(run&&(!['completed','approved','cancelled'].includes(run.status)||run.id!==run.latest_run_id))}>发送</button><button type="button" className="secondary" disabled={busy} onClick={()=>setRun(null)}>开始新对话</button></form>{error&&<p role="alert" className="error">{error}</p>}
 <details open><summary>我的对话（重新登录后可恢复）</summary>{sessions.map(s=><button className="text-button" key={s.id} disabled={busy} onClick={()=>void perform(async()=>setRun(await api('/agent/runs/'+s.latest_run_id)))}>{s.title} · {s.runs.length} 次运行</button>)}</details><details><summary>所有运行记录（历史只读，续聊请打开最新对话）</summary>{runs.map(r=><button className="text-button" key={r.id} disabled={busy} onClick={()=>void perform(async()=>setRun(await api('/agent/runs/'+r.id)))}>{r.id.slice(0,8)} · {status[r.status]}</button>)}</details>
 {run&&run.id!==run.latest_run_id&&<p role="status">当前显示历史运行，其他页面已继续此对话。<button type="button" className="text-button" disabled={busy} onClick={()=>void perform(async()=>setRun(await api('/agent/runs/'+run.latest_run_id)))}>打开最新运行</button></p>}
 {run&&!terminal&&<p role="status">{{connecting:'正在连接进度…',connected:'进度已连接',reconnecting:'连接中断，正在自动重连…',stopped:'进度连接已停止'}[connection]}{connection==='stopped'&&<button type="button" className="text-button" onClick={()=>{setError('');setConnectionAttempt(n=>n+1);}}>重新连接进度</button>}</p>}
 {run&&<div><details><summary>当前规划条件与上下文</summary><p>人数：{run.constraints?.servings||'使用厨房偏好'} · 用时：{run.constraints?.max_minutes?run.constraints.max_minutes+'分钟':'使用厨房偏好'}</p><p>厨具：{run.constraints?.equipment?.join('、')||'使用厨房偏好'} · 本轮排除：{run.constraints?.excluded_ingredients?.join('、')||'无额外排除（仍遵守已保存忌口）'}</p><p>补购预算：{run.constraints?.budget==null?'未设置':run.constraints.budget+'元'} · 可选配料：{run.constraints?.include_optional?'使用':'不使用'}</p>{run.context_summary?.source_run_id&&<p>较长对话已截取近期文本；旧工具结果不用于判断当前库存，完整运行记录仍保留。</p>}</details><h3>{status[run.status]} · 已执行 {run.steps} 轮</h3>{displayMessages(run.messages,run.context_summary).map((m:any,i:number)=><p key={i} style={{whiteSpace:"pre-line"}}><b>{m.role==='user'?'你':'助手'}：</b>{m.content}</p>)}{run.result?.error&&<p role="alert">本次运行失败：{errorText(run.result.error)}</p>}
 {run.result?.response_source&&<p className="muted">推荐与下一步由本轮查询结果生成；库存变化后请重新查询。</p>}
 <details><summary>工具执行记录</summary>{run.events.map((e:any)=><div key={e.step}><h4>{e.step}. {e.tool} · {e.elapsed_ms} ms</h4><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(e.result,null,2)}</pre></div>)}</details>
 {run.status==='awaiting_confirmation'&&<section>{run.pending.preview?<><h3>确认{run.pending.preview.action}？</h3><p>{run.pending.preview.name}{run.pending.preview.servings?' · '+run.pending.preview.servings+' 人份':''}</p>{run.pending.preview.quantity&&<p>入库 {Number(run.pending.preview.quantity)} {{g:'克',ml:'毫升',piece:'个'}[run.pending.preview.unit as 'g'|'ml'|'piece']} · {run.pending.preview.location} · {run.pending.preview.expires_on||'到期日期未知'}</p>}{run.pending.preview.ingredients?.map((i:any,n:number)=><p key={n}>{i.name} · {Number(i.quantity)} {{g:'克',ml:'毫升',piece:'个'}[i.unit as 'g'|'ml'|'piece']}{i.archived?'（恢复数量后仍保持归档）':''}</p>)}<p>确认有效期15分钟。对象变化后需重新准备操作。</p></>:<><h3>确认保存这餐方案？</h3><p>{run.pending.state.recipe.name} · {run.events.at(-1)?.result.candidate.servings} 人份</p><p>仅保存方案，不会扣减库存。库存或偏好变化后，需重新提出方案。</p></>}<button disabled={busy} onClick={()=>void perform(async()=>{setRun(await mutate('/agent/runs/'+run.id+'/approve'));await onChanged();})}>{run.pending.preview?'确认'+run.pending.preview.action:'确认保存方案'}</button></section>}
 {run.status==='approved'&&run.result?.action&&<p role="status">{({prepare_inventory:'已入库',prepare_cooking:'已记录做饭并扣减库存',prepare_undo:'已撤销做饭并恢复食材'} as Record<string,string>)[run.result.action]}。可在库存或用餐记录页查看。</p>}
 <div className="row">{run.status==='ready'&&<button disabled={busy} onClick={()=>void perform(()=>advance(run))}>继续执行</button>}{['failed','running'].includes(run.status)&&<button disabled={busy} onClick={()=>void perform(async()=>{const ready=await mutate('/agent/runs/'+run.id+'/retry');await advance(ready);})}>恢复执行</button>}{!['approved','completed','cancelled'].includes(run.status)&&<button className="secondary" disabled={busy} onClick={()=>void perform(async()=>setRun(await mutate('/agent/runs/'+run.id+'/cancel')))}>取消本次运行</button>}</div></div>}
 </section>;
}
