import test from 'node:test';
import assert from 'node:assert/strict';
import {desktopContext,launchBrowser,makeApi,openPage,signUp,startFixture,useTab,testDate} from './support.mjs';

test('F7 two recipes, merged preview, checks and explicit inventory confirmation',async()=>{
 const server=process.env.F7_PREVIEW_URL?{url:process.env.F7_PREVIEW_URL,stop:async()=>{}}:await startFixture(0);
 let browser;
 try{
  browser=await launchBrowser();const context=await desktopContext(browser);const page=await openPage(context,server.url);
  const api=makeApi(server.url),username='f7_'+Date.now().toString(36),password='F7-preview-fixture-12';
  await signUp(page,username,password);const token=await api.signIn(username,password);
  const call=async(path,method='GET',body,key)=>{const r=await api.call(token,path,method,body,key);assert.ok(r.status<300,JSON.stringify(r));return r.data;};
  const egg=await call('/ingredients','POST',{name:'鸡蛋',unit:'piece'});
  for(const [name,quantity] of [['双蛋菜','2'],['三蛋菜','3']])await call('/recipes','POST',{name,servings:1,minutes:10,equipment:['煮锅'],source:'F7 fixture',steps:['煮熟'],ingredients:[{ingredient_id:egg.id,quantity,unit:'piece'}]});
  await call('/inventory','POST',{ingredient_id:egg.id,quantity:'3',unit:'piece'},crypto.randomUUID());
  await call('/quotes','POST',{ingredient_id:egg.id,package_quantity:'6',package_price:'6',source:'本地测试报价',observed_on:testDate(),expected_version:0},crypto.randomUUID());
  await page.getByRole('button',{name:'刷新库存',exact:true}).click();
  await useTab(page,'我的菜谱');
  for(const name of ['双蛋菜','三蛋菜'])await page.locator('.recipe-grid .recipe').filter({has:page.getByRole('heading',{name,exact:true})}).getByRole('button',{name:'加入采购组合'}).click();
  await page.locator('.recipe-grid .recipe').first().getByRole('button',{name:'加入采购组合'}).click();
  assert.equal(await page.locator('.combination-row').count(),2);
  await page.getByRole('button',{name:'计算采购',exact:true}).click();
  const preview=page.locator('.combined-preview');await preview.getByText('总需求 5 个 · 有效库存 3 · 缺口 2',{exact:true}).waitFor();
  assert.match(await preview.innerText(),/购买1包，共6个，估价 ¥6/);
  assert.match(await preview.innerText(),/双蛋菜：2个/);assert.match(await preview.innerText(),/三蛋菜：3个/);
  if(process.env.F7_PREVIEW_URL)await page.screenshot({path:'.tmp-e2e/f7-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await useTab(page,'报价与采购');
  await page.getByRole('button',{name:'刷新报价与采购',exact:true}).waitFor();
  await page.getByRole('button',{name:'保存组合采购清单'}).click();
  await page.getByRole('heading',{name:'买好需要的，记入厨房',exact:true}).waitFor();
  await page.getByLabel('已买 · 鸡蛋',{exact:true}).waitFor();
  assert.equal(await page.locator('.combination-panel').count(),1);
  assert.equal(await page.locator('.combination-row').count(),0);
  assert.equal((await call('/inventory')).length,1);
  assert.equal(await page.getByRole('button',{name:'核对并入库',exact:true}).isDisabled(),true);
  const checkedResponse=page.waitForResponse(r=>r.url().endsWith('/check')&&r.request().method()==='POST');
  await page.getByLabel('已买 · 鸡蛋',{exact:true}).click();assert.equal((await checkedResponse).status(),200);
  await page.getByRole('button',{name:'刷新报价与采购',exact:true}).click();
  assert.equal(await page.getByLabel('已买 · 鸡蛋',{exact:true}).isChecked(),true);
  assert.equal((await call('/inventory')).length,1);
  const quantity=page.getByLabel('实际购买量（个）',{exact:true});
  await quantity.fill('7');
  await page.getByRole('button',{name:'刷新报价与采购',exact:true}).click();
  assert.equal(await quantity.inputValue(),'7');
  await quantity.fill('6');await page.getByLabel('本项实际总价（元，可留空）',{exact:true}).fill('6');
  await page.getByRole('button',{name:'保存采购修改',exact:true}).click();
  await page.getByText('草稿已保存，尚未入库。',{exact:true}).waitFor();
  await page.getByRole('button',{name:'核对并入库',exact:true}).click();
  await page.getByRole('group',{name:'采购确认'}).waitFor();
  if(process.env.F7_PREVIEW_URL)await page.screenshot({path:'.tmp-e2e/f7-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  const response=page.waitForResponse(r=>r.url().includes('/shopping/')&&r.url().endsWith('/confirm'));
  await page.getByRole('button',{name:'确认已购买并整单入库',exact:true}).click();
  const confirmed=await response;assert.equal(confirmed.status(),200);
  const req=confirmed.request();const replay=await call(new URL(req.url()).pathname.replace('/api/v1',''),'POST',req.postDataJSON(),req.headers()['idempotency-key']);
  assert.equal(replay.status,'completed');
  await page.getByText('整单已入库。请到菜谱页按当前库存更新方案。',{exact:true}).waitFor();
  const batches=await call('/inventory');assert.equal(batches.length,2);assert.equal(batches.reduce((s,b)=>s+Number(b.quantity),0),9);
  assert.equal((await call('/shopping'))[0].status,'completed');assert.deepEqual(await call('/cooking'),[]);assert.deepEqual(page.problems,[]);
  await context.close();
 }finally{await browser?.close();await server.stop();}
});
