import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {desktopContext,launchBrowser,makeApi,openPage,shot,signIn,startFixture,useTab,waitText} from './support.mjs';

let server,browser,api;
const PASSWORD='receipt-fixture-1';
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4//8/AAX+Av4N70a4AAAAAElFTkSuQmCC','base64');
before(async()=>{server=await startFixture(0);browser=await launchBrowser();api=makeApi(server.url);});
after(async()=>{await browser?.close();await server?.stop();});

test('小票私有上传、未知字段、丢包重试与重登录恢复，核对后整单入库',async()=>{
 const user='ui_receipts_0908';
 await api.call(null,'/auth/register','POST',{username:user,password:PASSWORD});
 const token=await api.signIn(user,PASSWORD);
 const ingredient=(await api.call(token,'/ingredients','POST',{name:'鸡蛋',unit:'piece'})).data;
 const context=await desktopContext(browser);
 try{
  const page=await openPage(context,server.url);
  await signIn(page,user,PASSWORD);
  await useTab(page,'小票录入');
  await page.getByLabel('小票图片').setInputFiles({name:'test.png',mimeType:'image/png',buffer:image});
  const uploadUrl=server.url+'/api/v1/receipts';
  await page.route(uploadUrl,async route=>{if(route.request().method()==='POST'){await route.fetch();await route.abort('failed');}else await route.continue();});
  await page.getByRole('button',{name:'上传小票',exact:true}).click();
  await waitText(page,/无法连接服务器/);
  assert.equal((await api.call(token,'/receipts')).data.length,1);
  await page.unroute(uploadUrl);
  await page.getByRole('button',{name:'上传小票',exact:true}).click();
  await waitText(page,/小票已私有保存/);
  assert.equal((await api.call(token,'/receipts')).data.length,1,'丢包重试应复用同一个上传操作');
  await page.getByRole('button',{name:'查看原图',exact:true}).click();
  await page.getByAltText('当前核对的小票原图').waitFor();
  await page.waitForFunction(()=>{const image=document.querySelector('img[alt="当前核对的小票原图"]');return image?.complete&&image.naturalWidth>0;});
  await page.getByRole('button',{name:'关闭原图',exact:true}).click();
  await page.getByRole('button',{name:'添加小票行'}).click();
  await page.getByLabel('小票名称').fill('鲜鸡蛋');
  await page.getByLabel('对应食材').selectOption(ingredient.id);
  await page.getByLabel('本项金额（元）').fill('6.50');
  await page.getByRole('button',{name:'保存小票草稿'}).click();
  await waitText(page,/小票草稿已保存/);
  let saved=(await api.call(token,'/receipts')).data[0];
  assert.equal(saved.version,2);
  assert.equal(saved.draft.items[0].quantity,null);
  assert.equal(saved.draft.items[0].unit,null);
  assert.equal(saved.draft.items[0].uncertain,true);
  assert.deepEqual((await api.call(token,'/inventory')).data,[]);
  await page.reload();
  await signIn(page,user,PASSWORD);
  await useTab(page,'小票录入');
  await waitText(page,/小票 · 版本 2/);
  assert.equal(await page.getByLabel('小票名称').inputValue(),'鲜鸡蛋');
  assert.equal(await page.getByLabel('数量（未知留空）').inputValue(),'');
  await page.getByLabel('数量（未知留空）').fill('6');
  await page.getByLabel('小票单位',{exact:true}).selectOption('piece');
  await page.getByLabel('仍需核对').uncheck();
  await page.getByRole('button',{name:'保存小票草稿'}).click();
  await waitText(page,/小票 · 版本 3/);
  saved=(await api.call(token,'/receipts')).data[0];
  assert.equal(saved.draft.items[0].quantity,'6');
  assert.equal(saved.draft.items[0].uncertain,false);
  assert.deepEqual((await api.call(token,'/inventory')).data,[]);
  await page.getByRole('button',{name:'核对小票入库',exact:true}).click();
  assert.deepEqual((await api.call(token,'/inventory')).data,[],'第一步核对不能写库存');
  const confirmUrl=server.url+'/api/v1/receipts/'+saved.id+'/confirm';
  await page.route(confirmUrl,async route=>{await route.fetch();await route.abort('failed');});
  await page.getByRole('button',{name:'确认小票并整单入库',exact:true}).click();
  await waitText(page,/无法连接服务器/);
  assert.equal((await api.call(token,'/inventory')).data.length,1);
  await page.unroute(confirmUrl);
  await page.getByRole('button',{name:'确认小票并整单入库',exact:true}).click();
  await waitText(page,/小票已整单入库/);
  assert.equal((await api.call(token,'/inventory')).data.length,1,'确认丢包重试不得重复入库');
  assert.equal((await api.call(token,'/inventory/events')).data.length,1);
  assert.equal(await page.getByRole('button',{name:'核对小票入库',exact:true}).count(),0);
  await page.reload();
  await signIn(page,user,PASSWORD);
  await useTab(page,'小票录入');
  await waitText(page,/已新增 1 个库存批次/);
  await shot(page,'receipt-confirmed.png');
  await api.call(null,'/auth/register','POST',{username:'ui_receipt_other',password:PASSWORD});
  await page.getByRole('button',{name:'退出登录'}).click();
  await signIn(page,'ui_receipt_other',PASSWORD);
  await useTab(page,'小票录入');
  await waitText(page,/还没有小票记录/);
  assert.equal(await page.locator('.receipt-editor').count(),0);
  assert.deepEqual(page.problems,[]);
 }finally{await context.close();}
});

test('取消小票后刷新仍为终态且不能入库',async()=>{
 const user='ui_receipt_cancel';
 await api.call(null,'/auth/register','POST',{username:user,password:PASSWORD});
 const token=await api.signIn(user,PASSWORD);
 const context=await desktopContext(browser);
 try{
  const page=await openPage(context,server.url);
  await signIn(page,user,PASSWORD);
  await useTab(page,'小票录入');
  await page.getByLabel('小票图片').setInputFiles({name:'cancel.png',mimeType:'image/png',buffer:image});
  await page.getByRole('button',{name:'上传小票',exact:true}).click();
  await waitText(page,/小票已私有保存/);
  await page.getByRole('button',{name:'取消小票',exact:true}).click();
  await waitText(page,/小票已取消/);
  await page.reload();
  await signIn(page,user,PASSWORD);
  await useTab(page,'小票录入');
  await waitText(page,/已取消/);
  assert.equal(await page.getByRole('button',{name:'核对小票入库',exact:true}).count(),0);
  assert.equal((await api.call(token,'/receipts')).data[0].status,'cancelled');
  assert.deepEqual((await api.call(token,'/inventory')).data,[]);
  assert.deepEqual(page.problems,[]);
 }finally{await context.close();}
});


test('窄屏小票显示单位冲突和确认失败，修正后只入库一次',async()=>{
 const user='ui_receipt_units';
 await api.call(null,'/auth/register','POST',{username:user,password:PASSWORD});
 const token=await api.signIn(user,PASSWORD);
 const ingredient=(await api.call(token,'/ingredients','POST',{name:'大米',unit:'g'})).data;
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'zh-CN'});
 try{
  const page=await openPage(context,server.url);
  await signIn(page,user,PASSWORD);
  await useTab(page,'小票录入');
  await page.getByLabel('小票图片').setInputFiles({name:'units.png',mimeType:'image/png',buffer:image});
  await page.getByRole('button',{name:'上传小票',exact:true}).click();
  await waitText(page,/小票已私有保存/);
  await page.getByRole('button',{name:'添加小票行'}).click();
  await page.getByLabel('小票名称').fill('测试大米');
  await page.getByLabel('对应食材').selectOption(ingredient.id);
  await page.getByLabel('数量（未知留空）').fill('7');
  await page.getByLabel('小票单位',{exact:true}).selectOption('piece');
  await page.getByLabel('仍需核对').uncheck();
  await page.getByRole('button',{name:'保存小票草稿'}).click();
  await waitText(page,/小票 · 版本 2/);
  const alert=page.locator('.purchase-line').getByRole('alert');
  assert.match(await alert.innerText(),/不能直接换算/);
  assert.equal(await page.getByRole('button',{name:'核对小票入库',exact:true}).isDisabled(),true);
  assert.deepEqual((await api.call(token,'/inventory')).data,[]);
  await page.getByLabel('数量（未知留空）').fill('0.7');
  await page.getByLabel('小票单位',{exact:true}).selectOption('kg');
  await page.getByRole('button',{name:'保存小票草稿'}).click();
  await waitText(page,/小票 · 版本 3/);
  await page.getByRole('button',{name:'核对小票入库',exact:true}).click();
  const saved=(await api.call(token,'/receipts')).data[0];
  const url=server.url+'/api/v1/receipts/'+saved.id+'/confirm';
  await page.route(url,route=>route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({error:{code:'UNIT_AMBIGUOUS'}})}));
  await page.getByRole('button',{name:'确认小票并整单入库',exact:true}).click();
  const failure=page.locator('.receipt-editor').getByRole('alert');
  await failure.waitFor();
  assert.match(await failure.innerText(),/单位不能直接换算/);
  const box=await failure.boundingBox();
  assert.ok(box.y>=0&&box.y+box.height<=844,'错误应在点击后的手机视口内');
  assert.deepEqual((await api.call(token,'/inventory')).data,[]);
  await shot(page,'receipt-unit-failure-mobile.png');
  await page.unroute(url);
  await page.getByRole('button',{name:'确认小票并整单入库',exact:true}).click();
  await waitText(page,/小票已整单入库/);
  const stock=(await api.call(token,'/inventory')).data;
  assert.equal(stock.length,1);
  assert.equal(Number(stock[0].quantity),700);
  assert.equal((await api.call(token,'/inventory/events')).data.length,1);
 }finally{await context.close();}
});
