"""food_inventory"""

import sqlalchemy as sa
from alembic import op

revision = "9290b526fd6e"
down_revision = "0001_identity"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cooking_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("recipe_snapshot", sa.JSON(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id", name="uq_cook_owner"),
    )
    op.create_index(
        op.f("ix_cooking_records_user_id"), "cooking_records", ["user_id"], unique=False
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id", name="uq_ingredient_owner"),
        sa.UniqueConstraint("user_id", "name", name="uq_ingredient_name"),
    )
    op.create_index(op.f("ix_ingredients_user_id"), "ingredients", ["user_id"], unique=False)
    op.create_table(
        "operations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id", name="uq_operation_owner"),
        sa.UniqueConstraint("user_id", "key", name="uq_operation_key"),
    )
    op.create_index(op.f("ix_operations_user_id"), "operations", ["user_id"], unique=False)
    op.create_table(
        "recipes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("equipment", sa.JSON(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id", name="uq_recipe_owner"),
    )
    op.create_index(op.f("ix_recipes_user_id"), "recipes", ["user_id"], unique=False)
    op.create_table(
        "ingredient_aliases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("ingredient_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id", "user_id"],
            ["ingredients.id", "ingredients.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "alias", name="uq_alias_owner"),
    )
    op.create_index(
        op.f("ix_ingredient_aliases_user_id"), "ingredient_aliases", ["user_id"], unique=False
    )
    op.create_table(
        "inventory_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("ingredient_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("expiry_source", sa.String(length=16), nullable=False),
        sa.Column("location", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("quantity >= 0", name="ck_batch_nonnegative"),
        sa.ForeignKeyConstraint(
            ["ingredient_id", "user_id"],
            ["ingredients.id", "ingredients.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id", name="uq_batch_owner"),
    )
    op.create_index(
        op.f("ix_inventory_batches_user_id"), "inventory_batches", ["user_id"], unique=False
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("recipe_id", sa.String(length=36), nullable=False),
        sa.Column("ingredient_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_recipe_quantity"),
        sa.ForeignKeyConstraint(
            ["ingredient_id", "user_id"],
            ["ingredients.id", "ingredients.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id", "user_id"],
            ["recipes.id", "recipes.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "ingredient_id", name="uq_recipe_ingredient"),
    )
    op.create_table(
        "cooking_consumptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("cooking_id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_consumption_quantity"),
        sa.ForeignKeyConstraint(
            ["batch_id", "user_id"],
            ["inventory_batches.id", "inventory_batches.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cooking_id", "user_id"],
            ["cooking_records.id", "cooking_records.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cooking_consumptions_cooking_id"),
        "cooking_consumptions",
        ["cooking_id"],
        unique=False,
    )
    op.create_table(
        "inventory_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("delta", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("reason", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id", "user_id"],
            ["inventory_batches.id", "inventory_batches.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["operation_id", "user_id"],
            ["operations.id", "operations.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_events_user_id"), "inventory_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory_events")
    op.drop_table("cooking_consumptions")
    op.drop_table("recipe_ingredients")
    op.drop_table("inventory_batches")
    op.drop_table("ingredient_aliases")
    op.drop_table("recipes")
    op.drop_table("operations")
    op.drop_table("ingredients")
    op.drop_table("cooking_records")
    # ### end Alembic commands ###
