"""optional_ingredients"""

import sqlalchemy as sa
from alembic import op

revision = "92d9cff900d6"
down_revision = "b04b9448a35e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredients", sa.Column("is_staple", sa.Boolean(), server_default="0", nullable=False)
    )
    op.add_column(
        "recipe_ingredients",
        sa.Column("optional", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe_ingredients", "optional")
    op.drop_column("ingredients", "is_staple")
    # ### end Alembic commands ###
