"""agent_events"""

import sqlalchemy as sa
from alembic import op

revision = "b04b9448a35e"
down_revision = "bd048bb65ef9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_run_events",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id", "user_id"],
            ["agent_runs.id", "agent_runs.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "seq"),
    )
    op.create_index(
        op.f("ix_agent_run_events_user_id"), "agent_run_events", ["user_id"], unique=False
    )
    op.add_column(
        "agent_runs", sa.Column("event_seq", sa.Integer(), server_default="0", nullable=False)
    )
    bind = op.get_bind()
    runs = sa.table(
        "agent_runs",
        sa.column("id", sa.String()),
        sa.column("user_id", sa.String()),
        sa.column("status", sa.String()),
        sa.column("steps", sa.Integer()),
        sa.column("event_seq", sa.Integer()),
    )
    events = sa.table(
        "agent_run_events",
        sa.column("run_id", sa.String()),
        sa.column("user_id", sa.String()),
        sa.column("seq", sa.Integer()),
        sa.column("payload", sa.JSON()),
    )
    for row in bind.execute(sa.select(runs)).mappings().all():
        bind.execute(
            events.insert().values(
                run_id=row["id"],
                user_id=row["user_id"],
                seq=1,
                payload={"status": row["status"], "steps": row["steps"], "event_seq": 1},
            )
        )
    bind.execute(runs.update().values(event_seq=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "event_seq")
    op.drop_table("agent_run_events")
    # ### end Alembic commands ###
